name: Update Calendar
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          go mod tidy
          go get github.com/go-git/go-git/v5
          go get github.com/apognu/gocal
          go get -d ./...

      - name: Build
        run: go build -v ./calendarSyncHandler.go

      - name: Run the script
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          ./calendarSyncHandler

      - name: Push changes to GitHub
        if: success()
        run: |
          git add calendar.html
          git commit -m "Automated update of calendar"
          git push origin main
